version: 2.1

orbs:
  node: circleci/node@4.0.0 # Use the Node orb for convenience
  aws-cli: circleci/aws-cli@4.0 # Use the AWS CLI orb

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.0 # Updated to Node.js version 18
    steps:
      - checkout
      - node/install-packages: # Install project dependencies
          pkg-manager: npm
      - aws-cli/setup:
          profile_name: default
      - run:
          name: Install AWS CDK
          command: npm install -g aws-cdk
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Synthesize CloudFormation Template
          command: cdk synth
      - run:
          name: Deploy CDK Stack
          command: cdk deploy --require-approval never
      - run:
          name: Retrieve CDK Stack Outputs
          command: |
            aws cloudformation describe-stacks --stack-name CdkStepFunctionStack --query "Stacks[0].Outputs" > cdk-outputs.json
      - run:
          name: Set Environment Variables
          command: |
            STATE_MACHINE_ARN=$(jq -r '.[] | select(.OutputKey=="StateMachineArnOutput") | .OutputValue' cdk-outputs.json)
            echo "export STATE_MACHINE_ARN=${STATE_MACHINE_ARN}" >> $BASH_ENV
            source $BASH_ENV
      - run: # Added step to run tests
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build-and-deploy
