version: 2.1

orbs:
  node: circleci/node@4.0.0 # Use the Node orb for convenience
  aws-cli: circleci/aws-cli@2.0.0 # Use the AWS CLI orb

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.0 # Updated to Node.js version 18
    steps:
      - checkout
      - node/install-packages: # Install project dependencies
          pkg-manager: npm
      - run:
          name: Install AWS CDK
          command: npm install -g aws-cdk
      - run:
          name: Synthesize CloudFormation Template
          command: cdk synth
      - run:
          name: Deploy CDK Stack
          command: cdk deploy --require-approval never
      - aws-cli/setup: # Set up AWS CLI with stored credentials
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build-and-deploy
